//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSApplicationDelegate-Protocol.h"
#import "PADProductDelegate-Protocol.h"
#import "PaddleDelegate-Protocol.h"

@class MECSidebarButton, MECore, NSArray, NSButton, NSMenuItem, NSSegmentedControl, NSString, NSTextField, NSTextView, NSView, NSWindow, PADProduct, Paddle, SUUpdater, infoWindow, progressWindow;

__attribute__((visibility("hidden")))
@interface AppDelegate : NSObject <NSApplicationDelegate, PaddleDelegate, PADProductDelegate>
{
    struct AuthorizationOpaqueRef *_authRef;
    NSWindow *_mainWindow;
    NSWindow *_prefWindow;
    progressWindow *_progressWindow;
    infoWindow *_infoWindow;
    SUUpdater *_myUpdater;
    Paddle *_paddle;
    PADProduct *_paddleProduct;
    NSString *_adURL;
    NSArray *_adArray;
    long long _lastAD;
    NSMenuItem *_buttonMenuPurchase;
    MECore *_sidebarController;
    MECSidebarButton *_sidebarTheme;
    MECSidebarButton *_sidebarStore;
    MECSidebarButton *_sidebarApps;
    MECSidebarButton *_sidebarFolders;
    MECSidebarButton *_sidebarSystemApps;
    MECSidebarButton *_sidebarSystemFolders;
    MECSidebarButton *_sidebarSystemExtensions;
    MECSidebarButton *_sidebarSystemDisks;
    MECSidebarButton *_sidebarDiscord;
    MECSidebarButton *_sidebarAdvert;
    MECSidebarButton *_sidebarAccount;
    NSSegmentedControl *_aboutSelector;
    NSSegmentedControl *_preferencesTabController;
    NSView *_preferencesGeneral;
    NSView *_preferencesLicense;
    NSView *_preferencesAbout;
    NSButton *_prefsQuickTips;
    NSButton *_autoTheme;
    NSButton *_hideAdverts;
    NSButton *_hideDiscord;
    NSButton *_paddlePurchaseOrLicense;
    NSButton *_paddleRecoverOr;
    NSButton *_paddleActivateOrDeactivate;
    NSTextField *_paddle_email_field;
    NSTextField *_paddle_license_field;
    NSTextField *_appName;
    NSTextField *_appVersion;
    NSTextField *_hlpVersion;
    NSTextField *_bndVersion;
    NSTextField *_appCopyright;
    NSTextView *_changeLog;
    NSView *_tabMain;
    NSView *_paddleView;
    NSView *_systemFoldersView;
    NSView *_systemAppsView;
    NSView *_systemExtensionsView;
    NSView *_systemDrivesView;
    NSTextField *_extensionAdd;
}

- (void).cxx_destruct;
@property(retain) NSTextField *extensionAdd; // @synthesize extensionAdd=_extensionAdd;
@property(retain) NSView *systemDrivesView; // @synthesize systemDrivesView=_systemDrivesView;
@property(retain) NSView *systemExtensionsView; // @synthesize systemExtensionsView=_systemExtensionsView;
@property(retain) NSView *systemAppsView; // @synthesize systemAppsView=_systemAppsView;
@property(retain) NSView *systemFoldersView; // @synthesize systemFoldersView=_systemFoldersView;
@property(retain) NSView *paddleView; // @synthesize paddleView=_paddleView;
@property(retain) NSView *tabMain; // @synthesize tabMain=_tabMain;
@property(retain) NSTextView *changeLog; // @synthesize changeLog=_changeLog;
@property(retain) NSTextField *appCopyright; // @synthesize appCopyright=_appCopyright;
@property(retain) NSTextField *bndVersion; // @synthesize bndVersion=_bndVersion;
@property(retain) NSTextField *hlpVersion; // @synthesize hlpVersion=_hlpVersion;
@property(retain) NSTextField *appVersion; // @synthesize appVersion=_appVersion;
@property(retain) NSTextField *appName; // @synthesize appName=_appName;
@property(retain) NSTextField *paddle_license_field; // @synthesize paddle_license_field=_paddle_license_field;
@property(retain) NSTextField *paddle_email_field; // @synthesize paddle_email_field=_paddle_email_field;
@property(retain) NSButton *paddleActivateOrDeactivate; // @synthesize paddleActivateOrDeactivate=_paddleActivateOrDeactivate;
@property(retain) NSButton *paddleRecoverOr; // @synthesize paddleRecoverOr=_paddleRecoverOr;
@property(retain) NSButton *paddlePurchaseOrLicense; // @synthesize paddlePurchaseOrLicense=_paddlePurchaseOrLicense;
@property(retain) NSButton *hideDiscord; // @synthesize hideDiscord=_hideDiscord;
@property(retain) NSButton *hideAdverts; // @synthesize hideAdverts=_hideAdverts;
@property(retain) NSButton *autoTheme; // @synthesize autoTheme=_autoTheme;
@property(retain) NSButton *prefsQuickTips; // @synthesize prefsQuickTips=_prefsQuickTips;
@property(retain) NSView *preferencesAbout; // @synthesize preferencesAbout=_preferencesAbout;
@property(retain) NSView *preferencesLicense; // @synthesize preferencesLicense=_preferencesLicense;
@property(retain) NSView *preferencesGeneral; // @synthesize preferencesGeneral=_preferencesGeneral;
@property(retain) NSSegmentedControl *preferencesTabController; // @synthesize preferencesTabController=_preferencesTabController;
@property(retain) NSSegmentedControl *aboutSelector; // @synthesize aboutSelector=_aboutSelector;
@property(retain) MECSidebarButton *sidebarAccount; // @synthesize sidebarAccount=_sidebarAccount;
@property(retain) MECSidebarButton *sidebarAdvert; // @synthesize sidebarAdvert=_sidebarAdvert;
@property(retain) MECSidebarButton *sidebarDiscord; // @synthesize sidebarDiscord=_sidebarDiscord;
@property(retain) MECSidebarButton *sidebarSystemDisks; // @synthesize sidebarSystemDisks=_sidebarSystemDisks;
@property(retain) MECSidebarButton *sidebarSystemExtensions; // @synthesize sidebarSystemExtensions=_sidebarSystemExtensions;
@property(retain) MECSidebarButton *sidebarSystemFolders; // @synthesize sidebarSystemFolders=_sidebarSystemFolders;
@property(retain) MECSidebarButton *sidebarSystemApps; // @synthesize sidebarSystemApps=_sidebarSystemApps;
@property(retain) MECSidebarButton *sidebarFolders; // @synthesize sidebarFolders=_sidebarFolders;
@property(retain) MECSidebarButton *sidebarApps; // @synthesize sidebarApps=_sidebarApps;
@property(retain) MECSidebarButton *sidebarStore; // @synthesize sidebarStore=_sidebarStore;
@property(retain) MECSidebarButton *sidebarTheme; // @synthesize sidebarTheme=_sidebarTheme;
@property(retain) MECore *sidebarController; // @synthesize sidebarController=_sidebarController;
@property __weak NSMenuItem *buttonMenuPurchase; // @synthesize buttonMenuPurchase=_buttonMenuPurchase;
@property(nonatomic) long long lastAD; // @synthesize lastAD=_lastAD;
@property(retain, nonatomic) NSArray *adArray; // @synthesize adArray=_adArray;
@property(retain, nonatomic) NSString *adURL; // @synthesize adURL=_adURL;
@property(retain, nonatomic) PADProduct *paddleProduct; // @synthesize paddleProduct=_paddleProduct;
@property(retain, nonatomic) Paddle *paddle; // @synthesize paddle=_paddle;
@property(retain) SUUpdater *myUpdater; // @synthesize myUpdater=_myUpdater;
@property(retain) infoWindow *infoWindow; // @synthesize infoWindow=_infoWindow;
@property(retain) progressWindow *progressWindow; // @synthesize progressWindow=_progressWindow;
@property(retain) NSWindow *prefWindow; // @synthesize prefWindow=_prefWindow;
@property(retain) NSWindow *mainWindow; // @synthesize mainWindow=_mainWindow;
- (void)restartRequiredProcess:(unsigned long long)arg1;
- (void)nukeTheDock;
- (void)restoreAllIcons:(id)arg1;
- (void)restoreIconsTest:(id)arg1;
- (void)restoreIconsWithProgress:(id)arg1;
- (void)processItemRestore:(int)arg1 inArray:(id)arg2 currentProgress:(double)arg3;
- (void)updateItemsTest:(id)arg1;
- (void)updateIconsWithProgress:(id)arg1;
- (void)processItem:(int)arg1 inArray:(id)arg2 currentProgress:(double)arg3;
- (void)showProgress;
- (void)addExtension:(id)arg1;
- (void)showHelp:(id)arg1;
- (void)updateSidebar:(id)arg1;
- (void)pref_setFastToolTips:(id)arg1;
- (void)setupWindows;
- (void)updateAdButton;
- (void)keepThoseAdsFresh;
- (id)colorFromHexString:(id)arg1;
- (void)visit_ad:(id)arg1;
- (void)visit_discord:(id)arg1;
- (void)showPreferences:(id)arg1;
- (void)showAbout:(id)arg1;
- (BOOL)install:(id *)arg1;
- (BOOL)blessHelperWithLabel:(id)arg1 error:(id *)arg2;
- (BOOL)isBlessed;
- (BOOL)isHelperUpdated;
- (void)startPaddle;
- (void)showPurchaseOrLicense:(id)arg1;
- (void)showActivateOrDeactivate:(id)arg1;
- (void)recoverPaddle:(id)arg1;
- (void)checkActivationStatus;
- (id)willShowPaddleUIType:(long long)arg1 product:(id)arg2;
- (void)setCheckUpdates:(id)arg1;
- (void)prefBug:(id)arg1;
- (void)prefFeedback:(id)arg1;
- (void)prefDonate:(id)arg1;
- (void)prefAutoTheme:(id)arg1;
- (void)setupPreferencesViews;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)applicationWillFinishLaunching:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

