//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTextField.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface Bazinga : NSTextField
{
    NSString *_original;
}

- (void).cxx_destruct;
@property(retain) NSString *original; // @synthesize original=_original;
- (void)textDidChange:(id)arg1;
- (void)textDidEndEditing:(id)arg1;
- (void)textDidBeginEditing:(id)arg1;

@end

