//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSXPCConnection;
@protocol ISIconCacheServiceProtocol, IconChampPHProtocol;

__attribute__((visibility("hidden")))
@interface HelperProxy : NSObject
{
    id <ISIconCacheServiceProtocol> _iconServicesProxy;
    NSXPCConnection *_proxyConnection;
    id <IconChampPHProtocol> _proxy;
}

+ (id)hp;
- (void).cxx_destruct;
@property(retain) id <IconChampPHProtocol> proxy; // @synthesize proxy=_proxy;
@property(retain) NSXPCConnection *proxyConnection; // @synthesize proxyConnection=_proxyConnection;
@property(retain) id <ISIconCacheServiceProtocol> iconServicesProxy; // @synthesize iconServicesProxy=_iconServicesProxy;
- (void)allDiskIcons:(CDUnknownBlockType)arg1;
- (void)setIcon:(id)arg1 forDisk:(id)arg2;
- (void)setIcon:(id)arg1 forFolderType:(id)arg2;
- (void)setIcon:(id)arg1 forExtension:(id)arg2;
- (void)createCacheEntriesForIcon:(id)arg1 withIcon:(id)arg2;
- (void)setSystemIcon:(id)arg1;
- (void)removeCacheEntriesForIcon:(id)arg1;
- (BOOL)setIcon:(id)arg1 forFile:(id)arg2;
- (void)setIcon:(id)arg1;
- (void)cacheRestore;
- (void)cacheBackup;
- (void)cacheReset;
- (id)init;

@end

