//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSImage, NSString;

__attribute__((visibility("hidden")))
@interface ICIconObject : NSObject
{
    unsigned char _isInTheme;
    unsigned char _isaltered;
    unsigned char _notapplied;
    unsigned char _needsRestore;
    int _iconType;
    NSString *_iconTitle;
    NSString *_iconID;
    NSString *_pathTarget;
    NSString *_pathCustom;
    NSString *_pathAlias;
    NSString *_themeName;
    NSImage *_imageTheme;
    NSImage *_systemImage;
    NSImage *_customImage;
}

- (void).cxx_destruct;
@property unsigned char needsRestore; // @synthesize needsRestore=_needsRestore;
@property unsigned char notapplied; // @synthesize notapplied=_notapplied;
@property unsigned char isaltered; // @synthesize isaltered=_isaltered;
@property unsigned char isInTheme; // @synthesize isInTheme=_isInTheme;
@property(retain) NSImage *customImage; // @synthesize customImage=_customImage;
@property(retain) NSImage *systemImage; // @synthesize systemImage=_systemImage;
@property(retain) NSImage *imageTheme; // @synthesize imageTheme=_imageTheme;
@property(retain) NSString *themeName; // @synthesize themeName=_themeName;
@property(retain) NSString *pathAlias; // @synthesize pathAlias=_pathAlias;
@property(retain) NSString *pathCustom; // @synthesize pathCustom=_pathCustom;
@property(retain) NSString *pathTarget; // @synthesize pathTarget=_pathTarget;
@property(retain) NSString *iconID; // @synthesize iconID=_iconID;
@property(retain) NSString *iconTitle; // @synthesize iconTitle=_iconTitle;
@property int iconType; // @synthesize iconType=_iconType;
- (void)logObject;
- (id)typeStringValue;

@end

