//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface ICIconUpdater : NSObject
{
    NSMutableDictionary *_themeDict;
    NSMutableArray *_iconSet;
}

+ (void)restoreIconCache;
+ (void)updateIcon:(id)arg1;
+ (void)establishIconSet;
+ (void)getSystemImageForObject:(id)arg1:(CDUnknownBlockType)arg2;
+ (id)iconSetOfType:(id)arg1;
+ (id)iconSet;
+ (void)establishThemeDict;
+ (void)establishThemeNamed:(id)arg1;
+ (id)themeObjectFromFile:(id)arg1;
+ (id)themeNamed:(id)arg1;
+ (id)themeDict;
+ (int)typeForObject:(id)arg1;
+ (BOOL)fileIsAlias:(id)arg1;
+ (id)nameForFile:(id)arg1;
+ (id)share;
- (void).cxx_destruct;
@property(retain) NSMutableArray *iconSet; // @synthesize iconSet=_iconSet;
@property(retain) NSMutableDictionary *themeDict; // @synthesize themeDict=_themeDict;
- (void)setIcon:(id)arg1;
- (void)cachePreThemedIcon:(id)arg1 async:(unsigned char)arg2;
- (void)cacheImageAsIcns:(id)arg1 withID:(id)arg2;

@end

