//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class ICIconObject, NSButton, NSColor, NSImageView, NSTextField, NSTrackingArea;

__attribute__((visibility("hidden")))
@interface ICIconNSView : NSView
{
    BOOL _mouseInside;
    ICIconObject *_iconObject;
    NSImageView *_iv;
    NSTextField *_tf;
    NSButton *_remove;
    NSButton *_restore;
    NSButton *_reveal;
    NSButton *_apply;
    NSButton *_link;
    NSColor *_hoverColor;
    NSTrackingArea *_trackingArea;
}

- (void).cxx_destruct;
@property(nonatomic) BOOL mouseInside; // @synthesize mouseInside=_mouseInside;
@property(retain, nonatomic) NSTrackingArea *trackingArea; // @synthesize trackingArea=_trackingArea;
@property(retain, nonatomic) NSColor *hoverColor; // @synthesize hoverColor=_hoverColor;
@property(retain) NSButton *link; // @synthesize link=_link;
@property(retain) NSButton *apply; // @synthesize apply=_apply;
@property(retain) NSButton *reveal; // @synthesize reveal=_reveal;
@property(retain) NSButton *restore; // @synthesize restore=_restore;
@property(retain) NSButton *remove; // @synthesize remove=_remove;
@property(retain) NSTextField *tf; // @synthesize tf=_tf;
@property(retain) NSImageView *iv; // @synthesize iv=_iv;
@property(retain) ICIconObject *iconObject; // @synthesize iconObject=_iconObject;
- (void)selectTarget:(id)arg1;
- (void)setTarget:(id)arg1;
- (void)reset;
- (void)deleteItem;
- (void)show;
- (void)displayIconOptions;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)ensureTrackingArea;
- (void)updateTrackingAreas;
- (void)drawRect:(struct CGRect)arg1;
- (void)viewDidMoveToWindow;

@end

