//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSCollectionView.h>

#import "NSDraggingDestination-Protocol.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface IconCollectionView : NSCollectionView <NSDraggingDestination>
{
    unsigned long long _displayType;
    NSString *_filterText;
    NSString *_pathToSelectedTheme;
}

- (void).cxx_destruct;
@property(retain) NSString *pathToSelectedTheme; // @synthesize pathToSelectedTheme=_pathToSelectedTheme;
@property(retain) NSString *filterText; // @synthesize filterText=_filterText;
@property unsigned long long displayType; // @synthesize displayType=_displayType;
- (void)drawRect:(struct CGRect)arg1;
- (void)viewWillMoveToWindow:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

