//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray, NSData, NSImage, NSString;

@protocol IconChampPHProtocol
- (void)restoreCache:(void (^)(BOOL))arg1;
- (void)backupCache:(void (^)(BOOL))arg1;
- (void)resetIconCacheWithReply:(void (^)(BOOL))arg1;
- (void)setIcon:(NSImage *)arg1 forFile:(NSString *)arg2 withReply:(void (^)(BOOL))arg3;
- (void)priveldgedFileDelete:(NSString *)arg1 withReply:(void (^)(BOOL))arg2;
- (void)priveldgedFileOverWrite:(NSString *)arg1 withData:(NSData *)arg2 withReply:(void (^)(BOOL))arg3;
- (void)priveldgedFileWrite:(NSString *)arg1 withData:(NSData *)arg2 withReply:(void (^)(BOOL))arg3;
- (void)removeCacheEntriesForUUIDS:(NSArray *)arg1 reply:(void (^)(BOOL))arg2;
- (void)createCacheEntriesForUUIDS:(NSArray *)arg1 withData:(NSData *)arg2 reply:(void (^)(BOOL))arg3;
- (void)saveStoreUnits:(NSArray *)arg1 forUUIDs:(NSArray *)arg2;
@end

