//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindow.h>

@class NSTextView;

__attribute__((visibility("hidden")))
@interface infoWindow : NSWindow
{
    NSTextView *_infoField;
}

- (void).cxx_destruct;
@property(retain) NSTextView *infoField; // @synthesize infoField=_infoField;

@end

