//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSImage, NSNumber, NSString, NSURL;

__attribute__((visibility("hidden")))
@interface MALApp : NSObject
{
    NSString *_title;
    NSString *_bundleId;
    NSImage *_icon;
    NSURL *_path;
    NSNumber *_itemId;
    NSNumber *_type;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSNumber *type; // @synthesize type=_type;
@property(readonly, nonatomic) NSNumber *itemId; // @synthesize itemId=_itemId;
@property(readonly, nonatomic) NSURL *path; // @synthesize path=_path;
@property(readonly, nonatomic) NSImage *icon; // @synthesize icon=_icon;
@property(readonly, nonatomic) NSString *bundleId; // @synthesize bundleId=_bundleId;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
- (id)initWithSqlStatement:(struct sqlite3_stmt *)arg1;

@end

