//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface MAList : NSObject
{
    struct sqlite3 *_db;
    NSMutableArray *_apps;
}

+ (id)sharedInstance;
+ (id)apps;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *apps; // @synthesize apps=_apps;
@property struct sqlite3 *db; // @synthesize db=_db;
- (id)init;
- (void)refresh;
- (BOOL)createAppList;
- (id)getDbPath;

@end

