//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSTextView, NSView, NSWindow;

__attribute__((visibility("hidden")))
@interface MECore : NSObject
{
    unsigned long long _macOS;
    NSArray *_preferenceViews;
    NSArray *_sidebarTopButtons;
    NSArray *_sidebarBotButtons;
    NSView *_mainView;
    NSView *_footerView;
    NSWindow *_mainWindow;
    NSWindow *_prefWindow;
    NSTextView *_changeLog;
}

+ (id)sharedInstance;
+ (unsigned long long)macOS;
- (void).cxx_destruct;
@property(retain) NSTextView *changeLog; // @synthesize changeLog=_changeLog;
@property(retain) NSWindow *prefWindow; // @synthesize prefWindow=_prefWindow;
@property(retain) NSWindow *mainWindow; // @synthesize mainWindow=_mainWindow;
@property(retain) NSView *footerView; // @synthesize footerView=_footerView;
@property(retain) NSView *mainView; // @synthesize mainView=_mainView;
@property(retain) NSArray *sidebarBotButtons; // @synthesize sidebarBotButtons=_sidebarBotButtons;
@property(retain) NSArray *sidebarTopButtons; // @synthesize sidebarTopButtons=_sidebarTopButtons;
@property(retain) NSArray *preferenceViews; // @synthesize preferenceViews=_preferenceViews;
@property unsigned long long macOS; // @synthesize macOS=_macOS;
- (void)systemDarkModeChange:(id)arg1;
- (void)selectAboutInfo:(id)arg1;
- (void)selectPreference:(id)arg1;
- (void)setFooterSubView:(id)arg1;
- (void)setMainViewSubView:(id)arg1;
- (id)slideAnimation;
- (void)setViewSubViewWithScrollableView:(id)arg1:(id)arg2;
- (void)selectView:(id)arg1;
- (void)updateSidebarColor;
- (void)setupSidebar;
- (void)setupSidebar11;
- (id)imageResize:(id)arg1 newSize:(struct CGSize)arg2;
- (id)init;

@end

