//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MSACDelegateForwarder.h"

#import "MSACCustomApplicationDelegate-Protocol.h"

@class NSString;

@interface MSACAppDelegateForwarder : MSACDelegateForwarder <MSACCustomApplicationDelegate>
{
}

+ (void)resetSharedInstance;
+ (id)sharedInstance;
+ (void)load;
- (void)custom_setDelegate:(id)arg1;
- (long long *)swizzlingOnceToken;
- (Class)originalClassForSetDelegate;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

