//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MSACAbstractLog.h"

@class NSDictionary, NSString;

@interface MSACCustomPropertiesLog : MSACAbstractLog
{
    NSString *_type;
    NSDictionary *_properties;
}

+ (id)serializeProperty:(id)arg1;
@property(retain, nonatomic) NSDictionary *properties; // @synthesize properties=_properties;
- (void)setType:(id)arg1;
- (id)type;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)serializeToDictionary;
- (BOOL)isValid;
- (BOOL)isEqual:(id)arg1;
- (id)init;

@end

