//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, NSString;
@protocol MSACChannelGroupProtocol, MSACChannelProtocol, MSACChannelUnitProtocol, MSACLog, NSObject;

@protocol MSACChannelDelegate <NSObject>

@optional
- (BOOL)channelUnit:(id <MSACChannelUnitProtocol>)arg1 shouldFilterLog:(id <MSACLog>)arg2;
- (void)channel:(id <MSACChannelProtocol>)arg1 didResumeWithIdentifyingObject:(id <NSObject>)arg2;
- (void)channel:(id <MSACChannelProtocol>)arg1 didPauseWithIdentifyingObject:(id <NSObject>)arg2;
- (void)channel:(id <MSACChannelProtocol>)arg1 didSetEnabled:(BOOL)arg2 andDeleteDataOnDisabled:(BOOL)arg3;
- (void)channel:(id <MSACChannelProtocol>)arg1 didFailSendingLog:(id <MSACLog>)arg2 withError:(NSError *)arg3;
- (void)channel:(id <MSACChannelProtocol>)arg1 didSucceedSendingLog:(id <MSACLog>)arg2;
- (void)channel:(id <MSACChannelProtocol>)arg1 willSendLog:(id <MSACLog>)arg2;
- (void)channel:(id <MSACChannelProtocol>)arg1 didCompleteEnqueueingLog:(id <MSACLog>)arg2 internalId:(NSString *)arg3;
- (void)channel:(id <MSACChannelProtocol>)arg1 didPrepareLog:(id <MSACLog>)arg2 internalId:(NSString *)arg3 flags:(unsigned long long)arg4;
- (void)channel:(id <MSACChannelProtocol>)arg1 prepareLog:(id <MSACLog>)arg2;
- (void)channelGroup:(id <MSACChannelGroupProtocol>)arg1 didAddChannelUnit:(id <MSACChannelUnitProtocol>)arg2;
@end

