//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MSACChannelProtocol-Protocol.h"

@class MSACChannelUnitConfiguration, NSObject, NSString;
@protocol MSACLog, OS_dispatch_queue;

@protocol MSACChannelUnitProtocol <MSACChannelProtocol>
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *logsDispatchQueue;
@property(retain, nonatomic) MSACChannelUnitConfiguration *configuration;
- (void)checkPendingLogs;
- (void)resumeSendingLogsWithToken:(NSString *)arg1;
- (void)pauseSendingLogsWithToken:(NSString *)arg1;
- (void)enqueueItem:(id <MSACLog>)arg1 flags:(unsigned long long)arg2;
@end

