//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MSACChannelProtocol-Protocol.h"

@class MSACChannelUnitConfiguration, NSString;
@protocol MSACChannelUnitProtocol, MSACIngestionProtocol;

@protocol MSACChannelGroupProtocol <MSACChannelProtocol>
@property(retain, nonatomic) NSString *appSecret;
@property(retain, nonatomic) NSString *logUrl;
- (id <MSACChannelUnitProtocol>)channelUnitForGroupId:(NSString *)arg1;
- (void)setMaxStorageSize:(long long)arg1 completionHandler:(void (^)(BOOL))arg2;
- (id <MSACChannelUnitProtocol>)addChannelUnitWithConfiguration:(MSACChannelUnitConfiguration *)arg1 withIngestion:(id <MSACIngestionProtocol>)arg2;
- (id <MSACChannelUnitProtocol>)addChannelUnitWithConfiguration:(MSACChannelUnitConfiguration *)arg1;
@end

