//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MSACSerializableObject-Protocol.h"

@class MSACException, NSMutableArray, NSNumber, NSString;

@interface MSACThread : NSObject <MSACSerializableObject>
{
    NSNumber *_threadId;
    NSString *_name;
    NSMutableArray *_frames;
    MSACException *_exception;
}

@property(retain, nonatomic) MSACException *exception; // @synthesize exception=_exception;
@property(retain, nonatomic) NSMutableArray *frames; // @synthesize frames=_frames;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSNumber *threadId; // @synthesize threadId=_threadId;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isValid;
- (id)serializeToDictionary;
- (id)init;

@end

