//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol MSACCrashHandlerSetupDelegate;

@interface MSACWrapperCrashesHelper : NSObject
{
    id <MSACCrashHandlerSetupDelegate> _crashHandlerSetupDelegate;
}

+ (id)buildHandledErrorReportWithErrorID:(id)arg1;
+ (id)trackModelException:(id)arg1 withProperties:(id)arg2 withAttachments:(id)arg3;
+ (void)sendErrorAttachments:(id)arg1 withIncidentIdentifier:(id)arg2;
+ (BOOL)sendCrashReportsOrAwaitUserConfirmationForFilteredIds:(id)arg1;
+ (id)unprocessedCrashReports;
+ (BOOL)automaticProcessing;
+ (void)setAutomaticProcessing:(BOOL)arg1;
+ (id)getCrashHandlerSetupDelegate;
+ (id)crashHandlerSetupDelegate;
+ (void)setCrashHandlerSetupDelegate:(id)arg1;
+ (id)sharedInstance;
@property(nonatomic) __weak id <MSACCrashHandlerSetupDelegate> crashHandlerSetupDelegate; // @synthesize crashHandlerSetupDelegate=_crashHandlerSetupDelegate;
- (void).cxx_destruct;

@end

