//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MSACModel-Protocol.h"
#import "MSACSerializableObject-Protocol.h"

@class NSString;

@interface MSACLocExtension : NSObject <MSACSerializableObject, MSACModel>
{
    NSString *_tz;
}

@property(copy, nonatomic) NSString *tz; // @synthesize tz=_tz;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isValid;
- (id)serializeToDictionary;

@end

