//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MSACModel-Protocol.h"
#import "MSACSerializableObject-Protocol.h"

@class NSArray, NSString;

@interface MSACProtocolExtension : NSObject <MSACSerializableObject, MSACModel>
{
    NSArray *_ticketKeys;
    NSString *_devMake;
    NSString *_devModel;
}

@property(copy, nonatomic) NSString *devModel; // @synthesize devModel=_devModel;
@property(copy, nonatomic) NSString *devMake; // @synthesize devMake=_devMake;
@property(retain, nonatomic) NSArray *ticketKeys; // @synthesize ticketKeys=_ticketKeys;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isValid;
- (id)serializeToDictionary;

@end

