//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MSACChannelDelegate-Protocol.h"
#import "MSACChannelGroupProtocol-Protocol.h"

@class MSACAppCenterIngestion, NSHashTable, NSMutableArray, NSString;
@protocol MSACStorage, OS_dispatch_queue;

@interface MSACChannelGroupDefault : NSObject <MSACChannelDelegate, MSACChannelGroupProtocol>
{
    NSHashTable *_delegates;
    MSACAppCenterIngestion *_ingestion;
    id <MSACStorage> _storage;
    NSObject<OS_dispatch_queue> *_logsDispatchQueue;
    NSMutableArray *_channels;
}

@property(retain, nonatomic) NSMutableArray *channels; // @synthesize channels=_channels;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *logsDispatchQueue; // @synthesize logsDispatchQueue=_logsDispatchQueue;
@property(retain, nonatomic) id <MSACStorage> storage; // @synthesize storage=_storage;
@property(retain, nonatomic) MSACAppCenterIngestion *ingestion; // @synthesize ingestion=_ingestion;
@property(retain, nonatomic) NSHashTable *delegates; // @synthesize delegates=_delegates;
- (void).cxx_destruct;
- (void)setMaxStorageSize:(long long)arg1 completionHandler:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) NSString *logUrl;
@property(retain, nonatomic) NSString *appSecret;
- (void)resumeWithIdentifyingObject:(id)arg1;
- (void)pauseWithIdentifyingObject:(id)arg1;
- (void)setEnabled:(BOOL)arg1 andDeleteDataOnDisabled:(BOOL)arg2;
- (void)channel:(id)arg1 didResumeWithIdentifyingObject:(id)arg2;
- (void)channel:(id)arg1 didPauseWithIdentifyingObject:(id)arg2;
- (BOOL)channelUnit:(id)arg1 shouldFilterLog:(id)arg2;
- (void)channel:(id)arg1 didFailSendingLog:(id)arg2 withError:(id)arg3;
- (void)channel:(id)arg1 didSetEnabled:(BOOL)arg2 andDeleteDataOnDisabled:(BOOL)arg3;
- (void)channel:(id)arg1 didSucceedSendingLog:(id)arg2;
- (void)channel:(id)arg1 willSendLog:(id)arg2;
- (void)channel:(id)arg1 didCompleteEnqueueingLog:(id)arg2 internalId:(id)arg3;
- (void)channel:(id)arg1 didPrepareLog:(id)arg2 internalId:(id)arg3 flags:(unsigned long long)arg4;
- (void)channel:(id)arg1 prepareLog:(id)arg2;
- (void)enumerateDelegatesForSelector:(SEL)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)removeDelegate:(id)arg1;
- (void)addDelegate:(id)arg1;
- (id)channelUnitForGroupId:(id)arg1;
- (id)addChannelUnitWithConfiguration:(id)arg1 withIngestion:(id)arg2;
- (id)addChannelUnitWithConfiguration:(id)arg1;
- (id)initWithIngestion:(id)arg1;
- (id)initWithHttpClient:(id)arg1 installId:(id)arg2 logUrl:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

