//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray, NSData, NSDictionary, NSString, NSURL;
@protocol MSACHttpClientDelegate;

@protocol MSACHttpClientProtocol
@property(nonatomic) __weak id <MSACHttpClientDelegate> delegate;
- (void)setEnabled:(BOOL)arg1;
- (void)resume;
- (void)pause;
- (void)sendAsync:(NSURL *)arg1 method:(NSString *)arg2 headers:(NSDictionary *)arg3 data:(NSData *)arg4 retryIntervals:(NSArray *)arg5 compressionEnabled:(BOOL)arg6 completionHandler:(void (^)(NSData *, NSHTTPURLResponse *, NSError *))arg7;
- (void)sendAsync:(NSURL *)arg1 method:(NSString *)arg2 headers:(NSDictionary *)arg3 data:(NSData *)arg4 completionHandler:(void (^)(NSData *, NSHTTPURLResponse *, NSError *))arg5;
@end

