//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MSACHistoryInfo.h"

@class NSString;

@interface MSACTestSessionInfo : MSACHistoryInfo
{
    NSString *_sessionId;
}

@property(copy, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
- (void).cxx_destruct;
- (id)initWithTimestamp:(id)arg1 andSessionId:(id)arg2;

@end

