//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, NSString, PADAlert, PADDisplayConfiguration, PADProduct;

@protocol PaddleDelegate <NSObject>

@optional
- (NSString *)customStoragePath;
- (BOOL)canAutoActivate:(PADProduct *)arg1;
- (NSString *)appGroupForSharedLicense;
- (void)paddleDidError:(NSError *)arg1;
- (BOOL)willShowPaddleAlert:(PADAlert *)arg1;
- (void)didDismissPaddleUIType:(long long)arg1 triggeredUIType:(long long)arg2 product:(PADProduct *)arg3;
- (PADDisplayConfiguration *)willShowPaddleUIType:(long long)arg1 product:(PADProduct *)arg2;
@end

