//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSTableViewDataSource-Protocol.h"
#import "NSTableViewDelegate-Protocol.h"

@class IconCollectionView, IconCollectionViewManager, NSArray, NSString, ThemeTableView;

__attribute__((visibility("hidden")))
@interface ThemeTableManager : NSObject <NSTableViewDelegate, NSTableViewDataSource>
{
    NSArray *_themeIconList;
    NSArray *_themeList;
    NSString *_pathToSelectedTheme;
    ThemeTableView *_tv;
    IconCollectionViewManager *_acvm;
    IconCollectionView *_icv;
}

- (void).cxx_destruct;
@property(retain) IconCollectionView *icv; // @synthesize icv=_icv;
@property(retain) IconCollectionViewManager *acvm; // @synthesize acvm=_acvm;
@property(retain) ThemeTableView *tv; // @synthesize tv=_tv;
@property(retain) NSString *pathToSelectedTheme; // @synthesize pathToSelectedTheme=_pathToSelectedTheme;
@property(retain) NSArray *themeList; // @synthesize themeList=_themeList;
@property(retain) NSArray *themeIconList; // @synthesize themeIconList=_themeIconList;
- (void)trashTheme:(id)arg1;
- (void)showTheme:(id)arg1;
- (void)newTheme:(id)arg1;
- (BOOL)tableView:(id)arg1 acceptDrop:(id)arg2 row:(long long)arg3 dropOperation:(unsigned long long)arg4;
- (unsigned long long)tableView:(id)arg1 validateDrop:(id)arg2 proposedRow:(long long)arg3 proposedDropOperation:(unsigned long long)arg4;
- (void)tableViewSelectionDidChange:(id)arg1;
- (long long)numberOfRowsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (id)imageResize:(id)arg1 newSize:(struct CGSize)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

