//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableView.h>

#import "NSDraggingDestination-Protocol.h"

@class NSString, SGDirWatchdog;

__attribute__((visibility("hidden")))
@interface ThemeTableView : NSTableView <NSDraggingDestination>
{
    SGDirWatchdog *_watchDog;
}

- (void).cxx_destruct;
@property(retain) SGDirWatchdog *watchDog; // @synthesize watchDog=_watchDog;
- (BOOL)tableView:(id)arg1 acceptDrop:(id)arg2 row:(long long)arg3 dropOperation:(unsigned long long)arg4;
- (unsigned long long)tableView:(id)arg1 validateDrop:(id)arg2 proposedRow:(long long)arg3 proposedDropOperation:(unsigned long long)arg4;
- (void)viewWillMoveToWindow:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

